### ISSUE TITLE
основные изменения для удобной работы с менеджером

### ISSUE THREAD

**Issue by progreccor** [Delo-Design/quantummanager#12]
1. При открытии картинки кроп должен быть установлен по максимальным границам картинки:
![Imgur](https://i.imgur.com/ttAVT95.png)

2. у нас нет возможности уменьшить картинку до нужного размера.
Например, нам нужно получить картинку размером 800 на 600.

3. у нас показывается только текущий размер файла в пикселях. Нет информации о текущем размере файла в килобайтах. Причем желательно иметь и прогнозируемый размер файла, чтобы видеть какого размера он станет.

4. убираем лишние кнопки. Они не несут никакой функции.
![Imgur](https://i.imgur.com/9dsqCNb.png)

5. При нажатии кнопки "кроп" ожидается все таки обрезка картинки, чтобы видеть что получится перед записью файла.

6. не хватает кнопки для масштаба 1к1 (при уменьшении и увеличении файла), чтобы увидеть файл как он будет один к одному.

7. если я выбираю кнопку "выбрать" во вводном материале - у меня показывается последняя папка, к которой  я имел доступ. Я не могу быстро найти тот файл, который сейчас установлен в качестве вводного.
Нужно чтобы открывалась папка с этим файлом.
![Imgur](https://i.imgur.com/3aIQvEa.png)

![Imgur](https://i.imgur.com/NL6u0iL.png)

**Comment by dmitriitux** [comment]
1 - сделано
2 - сделано
4 - сделано
6 - частично сделано, при изменение пропорции пока изменяется и размер под холст, пока не разобрался до конца

**Comment by dmitriitux** [comment]
3 - сделано
7 - сделано
кроп полностью сейчас полностью переписывается, поэтому закрываю
