### ISSUE TITLE
Ключ к API Фотостока

### ISSUE THREAD

**Issue by kernusr** [Delo-Design/quantummanager#20]
Нужно добавить возможность, чтобы пользователь мог ввести собственный ключ от фотостока, вместо использования общего ключа. Это сэкономит общее кол-во запросов, для общего ключа и позволит пользователю увеличить собственное кол-во запросов

**Comment by proweb** [comment]
Полностью согласен, а то при увеличении пользовательской базы все лимиты просто сожрутся

**Comment by dmitriitux** [comment]
Когда будет виден горизонт за предел выхода, будет добавлено возможность ввести свой ключ для апи, сейчас в сутки доступно 120к запросов в 24 часа.
