### ISSUE TITLE
Разделить имя файла

### ISSUE THREAD

**Issue by ali-95** [Delo-Design/quantummanager#21]
Можно будет в будущем чтобы при загрузке файла он еще разделял слова нижними ( _ ) или ( - ) такими знаками, а то как то не очень выглядит когда два слова пишется слитно.
**Пример**
>Hello World

>helloworld

**вот так хорошо выглядит же**
>hello_world

**Comment by dmitriitux** [comment]
> Можно будет в будущем чтобы при загрузке файла он еще разделял слова нижними ( _ ) или ( - ) такими знаками, а то как то не очень выглядит когда два слова пишется слитно.
> **Пример**
> 
> > Hello World
> 
> > helloworld
> 
> **вот так хорошо выглядит же**
> 
> > hello_world

да, верно, надо сделать

**Comment by dmitriitux** [comment]
сделал так же и папкам, в следующем релизе будет, пример имени загружаемого файла "Привет Мир!" - получится "privet-mir"
