### ISSUE TITLE
Добрый день, Дмитрий! Транслитерацию бы названий загружаемых файлов 

### ISSUE THREAD

**Issue by bsakhanov** [Delo-Design/quantummanager#22]
Транслитерацию бы названий загружаемых файлов -- такую бы опцию добавить.
Чтобы при загрузке названия файлов автоматом могли в латиницу конвертироваться из кириллицы. С возможностью настройки ограниченного числа символов в названии (чтобы пользователь не мог загружать файлы с километровыми названиями) с прибавлением в конце названия небольшого хеша из случайных чисел для безопасности.

**Comment by dmitriitux** [comment]
Здравствуйте, сейчас же уже автоматически конвертируется, вас устроит настройка типа: «максимальное кол-во символов для файлов»? Дальше режется и добавляется хэш, да

**Comment by bsakhanov** [comment]
> Здравствуйте, сейчас же уже автоматически конвертируется, вас устроит настройка типа: «максимальное кол-во символов для файлов»? Дальше режется и добавляется хэш, да
Здорово! Да, такая настройка устроит!

**Comment by dmitriitux** [comment]
> > Здравствуйте, сейчас же уже автоматически конвертируется, вас устроит настройка типа: «максимальное кол-во символов для файлов»? Дальше режется и добавляется хэш, да
> > Здорово! Да, такая настройка устроит!

ок

**Comment by dmitriitux** [comment]
![2019-09-08_16-18-28](https://user-images.githubusercontent.com/6643167/64488781-91feee00-d254-11e9-8694-33b74535f2b2.png)
Настройка добавлена, в следующем релизе будет она.
