### ISSUE TITLE
Ошибка, если Joomla установлена в подпапку

### ISSUE THREAD

**Issue by b2z** [Delo-Design/quantummanager#23]
We just install quantum manager in a test website installed in subfolder. When Quantum open we have a "infinitite loading screen" we can't create or upload.

When we look at the firebug console we see a 404 and we understand :
The url request is www.xxxxxxxxxxxxxx/administrator/index.p...&path=root&name=test
but the sub folder is missing

https://www.norrnext.com/forum/quantum-manager/826-error-when-joomla-installed-in-a-subfolder

**Comment by dmitriitux** [comment]
Это уже решено, в следующем релизе будет исправлено
