### ISSUE TITLE
Кнопка добавления файла

### ISSUE THREAD

**Issue by b2z** [Delo-Design/quantummanager#24]
The user click
It open the quantum manager (maybe with a file extension filter but don't really needed for now)
He can upload, select etc media
When selected we can add a class (a class dropdown selector populate from Quantum global parameter will be perfect) and a title (text field) a target (_blank etc)
Insert button

https://www.norrnext.com/forum/quantum-manager/824-file-managment-pdf-xls-etc

**Comment by bsakhanov** [comment]
совершенно согласен! Нужна кнопка в визуальный редактор для добавления просто файла (не картинки) для скачивания.
И еще было бы очень здорово, если можно было бы переопределить для файлов-документов отдельно папку для загрузки (что не лежали все в одной куче -- и картинки, и документы).

**Comment by dmitriitux** [comment]
> совершенно согласен! Нужна кнопка в визуальный редактор для добавления просто файла (не картинки) для скачивания.
> И еще было бы очень здорово, если можно было бы переопределить для файлов-документов отдельно папку для загрузки (что не лежали все в одной куче -- и картинки, и документы).

понял, надо обдумать

**Comment by dmitriitux** [comment]
можно внедрить типы рут папок, я вижу пока такие "Документы", "Картинки", "Музыка", "Видео" и папки соответственно "docs", "images", "musics", "videos" и эти типы выгружать слева как табы, а дерево каталогов включается от этого типа тогда

**Comment by dmitriitux** [comment]
![2019-09-04_00-59-17](https://user-images.githubusercontent.com/6643167/64211551-3f69ae80-ceaf-11e9-9f51-5205b55aac22.png)
![2019-09-04_00-59-02](https://user-images.githubusercontent.com/6643167/64211552-40024500-ceaf-11e9-811f-50a36e71fabf.png)


> совершенно согласен! Нужна кнопка в визуальный редактор для добавления просто файла (не картинки) для скачивания.
> И еще было бы очень здорово, если можно было бы переопределить для файлов-документов отдельно папку для загрузки (что не лежали все в одной куче -- и картинки, и документы).

Вот что надумал, то есть теперь есть области, и можно добавлять будет свои, я думаю это наилучший выход, эти области можно внедрять как отдельные кнопки в редактор, или как одну, но с другим выводом

**Comment by b2z** [comment]
Отлично

**Comment by dmitriitux** [comment]
> Отлично, только убери ID и делай их на фоне. Пользователь не должен такие вещи видеть и ими управлять.

да, уберу, это просто набросок был, они будут из имени генерироваться

**Comment by bsakhanov** [comment]
> эти области можно внедрять как отдельные кнопки в редактор, или как одну, но с другим выводом

Отличное решение!

**Comment by dmitriitux** [comment]
Кнопка была добавлена в релизе 1.3. Через которую можно вставлять в материалы разные типы файлов.
